[package]
name = "transmute-formats"
version = "0.1.0"
edition = "2024"

[dependencies]
image.workspace = true
tracing.workspace = true
memmap2.workspace = true
thiserror.workspace = true

transmute-common.workspace = true

[dev-dependencies]
tempfile = "3.13"
